import argparse
import html
from pathlib import Path


def markdown_to_html_fallback(markdown_text: str, title: str) -> str:
    # Lightweight fallback renderer for environments without external markdown packages.
    lines = markdown_text.splitlines()
    out: list[str] = []
    out.append("<!doctype html>")
    out.append("<html lang=\"en\">")
    out.append("<head>")
    out.append("  <meta charset=\"utf-8\" />")
    out.append("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />")
    out.append(f"  <title>{html.escape(title)}</title>")
    out.append("  <style>")
    out.append("    :root { --bg:#f7f4ef; --card:#fffdfa; --text:#1f2328; --muted:#6b7280; --line:#d9d2c7; }")
    out.append("    body { margin:0; padding:32px 20px; background:linear-gradient(180deg,#f7f4ef 0%,#efe8dd 100%); color:var(--text); font:16px/1.55 Georgia, 'Times New Roman', serif; }")
    out.append("    .wrap { max-width:920px; margin:0 auto; background:var(--card); border:1px solid var(--line); border-radius:14px; padding:28px; box-shadow:0 8px 30px rgba(60,40,20,.08); }")
    out.append("    h1,h2,h3 { line-height:1.2; margin-top:1.3em; }")
    out.append("    h1 { font-size:2rem; margin-top:.2em; }")
    out.append("    h2 { font-size:1.35rem; border-bottom:1px solid var(--line); padding-bottom:6px; }")
    out.append("    p { margin:.65em 0; }")
    out.append("    ul { margin:.4em 0 .9em 1.2em; }")
    out.append("    li { margin:.2em 0; }")
    out.append("    code { background:#f3eee6; border:1px solid #e7dfd3; border-radius:4px; padding:1px 4px; }")
    out.append("    table { border-collapse:collapse; width:100%; margin:.8em 0 1.2em; }")
    out.append("    th, td { border:1px solid var(--line); padding:8px 10px; text-align:left; }")
    out.append("    th { background:#f4ede2; }")
    out.append("    img { max-width:100%; border:1px solid var(--line); border-radius:8px; }")
    out.append("    .muted { color:var(--muted); font-size:.92rem; }")
    out.append("    @media print { body { background:white; padding:0; } .wrap { border:none; box-shadow:none; } }")
    out.append("  </style>")
    out.append("</head>")
    out.append("<body>")
    out.append("  <main class=\"wrap\">")

    in_list = False
    in_table = False

    def close_structures() -> None:
        nonlocal in_list, in_table
        if in_list:
            out.append("    </ul>")
            in_list = False
        if in_table:
            out.append("    </tbody></table>")
            in_table = False

    for line in lines:
        stripped = line.strip()

        if not stripped:
            close_structures()
            continue

        if stripped.startswith("# "):
            close_structures()
            out.append(f"    <h1>{html.escape(stripped[2:].strip())}</h1>")
            continue
        if stripped.startswith("## "):
            close_structures()
            out.append(f"    <h2>{html.escape(stripped[3:].strip())}</h2>")
            continue
        if stripped.startswith("### "):
            close_structures()
            out.append(f"    <h3>{html.escape(stripped[4:].strip())}</h3>")
            continue

        if stripped.startswith("![") and "](" in stripped and stripped.endswith(")"):
            close_structures()
            alt = stripped[2:stripped.index("]")]
            src = stripped[stripped.index("(") + 1 : -1]
            out.append(f"    <p><img src=\"{html.escape(src)}\" alt=\"{html.escape(alt)}\" /></p>")
            continue

        if stripped.startswith("- "):
            if not in_list:
                close_structures()
                out.append("    <ul>")
                in_list = True
            item = stripped[2:].strip()
            out.append(f"      <li>{html.escape(item)}</li>")
            continue

        if stripped.startswith("|") and stripped.endswith("|"):
            cols = [c.strip() for c in stripped.strip("|").split("|")]
            if all(set(c) <= {"-", ":"} for c in cols):
                continue
            if not in_table:
                close_structures()
                out.append("    <table><tbody>")
                in_table = True
                out.append("      <tr>" + "".join(f"<th>{html.escape(c)}</th>" for c in cols) + "</tr>")
            else:
                out.append("      <tr>" + "".join(f"<td>{html.escape(c)}</td>" for c in cols) + "</tr>")
            continue

        close_structures()
        out.append(f"    <p>{html.escape(stripped)}</p>")

    close_structures()
    out.append("    <p class=\"muted\">Generated by scripts/export_sft_report_html.py</p>")
    out.append("  </main>")
    out.append("</body>")
    out.append("</html>")
    return "\n".join(out) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Export markdown SFT report to printable HTML")
    parser.add_argument(
        "--input",
        type=str,
        default="outputs/sft_math_sweep/report.md",
        help="Path to markdown report",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="outputs/sft_math_sweep/report.html",
        help="Path to HTML output",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="SFT MATH Experiment Report",
        help="HTML document title",
    )
    args = parser.parse_args()

    in_path = Path(args.input)
    if not in_path.exists():
        raise FileNotFoundError(
            f"Missing markdown report: {in_path}. Run scripts/generate_sft_math_report.py first."
        )

    markdown_text = in_path.read_text(encoding="utf-8")
    html_text = markdown_to_html_fallback(markdown_text, args.title)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html_text, encoding="utf-8")
    print(f"Wrote HTML report: {out_path.as_posix()}")


if __name__ == "__main__":
    main()
